# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecategory',
            old_name='to_category',
            new_name='images',
        ),
    ]
