# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 03:42
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170914_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecategory',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=website.models.get_upload_path, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
