# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 04:55
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170923_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_image',
            field=sorl.thumbnail.fields.ImageField(default='test.jpg', upload_to=website.models.get_upload_path),
            preserve_default=False,
        ),
    ]
